# Generated by Django 3.2.6 on 2021-09-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coment', '0002_delete_coment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, verbose_name='Имя')),
                ('task', models.TextField(blank=True, verbose_name='Вопрос')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публирован')),
                ('number', models.CharField(max_length=12, verbose_name='Номер отправителя')),
                ('otvet', models.TextField(blank=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос-ответь',
                'verbose_name_plural': 'Вопрос-ответь',
            },
        ),
    ]
