# Generated by Django 3.2.6 on 2021-08-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Last_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('datab', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('datas', models.DateTimeField(auto_now=True, verbose_name='Дата последного добавления')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фотография')),
                ('is_pblished', models.BooleanField(default=True, verbose_name='Публирован')),
            ],
            options={
                'verbose_name': 'Последные новости',
                'verbose_name_plural': 'Последные новости',
            },
        ),
    ]
