# Generated by Django 3.2.6 on 2021-08-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glav', '0002_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='task',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='title',
        ),
    ]
