# Generated by Django 3.2.6 on 2021-09-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glav', '0003_auto_20210830_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropdown_for',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('datab', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('datas', models.DateTimeField(auto_now=True, verbose_name='Дата последного добавления')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фотография')),
                ('is_pblished', models.BooleanField(default=True, verbose_name='Публирован')),
                ('silka', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Dropdown_for',
                'verbose_name_plural': 'Dropdown_for',
            },
        ),
        migrations.CreateModel(
            name='Dropdown_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('datab', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('datas', models.DateTimeField(auto_now=True, verbose_name='Дата последного добавления')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фотография')),
                ('is_pblished', models.BooleanField(default=True, verbose_name='Публирован')),
                ('silka', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Dropdown_one',
                'verbose_name_plural': 'Dropdown_one',
            },
        ),
        migrations.CreateModel(
            name='Dropdown_three',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('datab', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('datas', models.DateTimeField(auto_now=True, verbose_name='Дата последного добавления')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фотография')),
                ('is_pblished', models.BooleanField(default=True, verbose_name='Публирован')),
                ('silka', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Dropdown_three',
                'verbose_name_plural': 'Dropdown_three',
            },
        ),
        migrations.CreateModel(
            name='Dropdown_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('datab', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('datas', models.DateTimeField(auto_now=True, verbose_name='Дата последного добавления')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фотография')),
                ('is_pblished', models.BooleanField(default=True, verbose_name='Публирован')),
                ('silka', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Dropdown_two',
                'verbose_name_plural': 'Dropdown_two',
            },
        ),
        migrations.DeleteModel(
            name='Last_new',
        ),
    ]
