# Generated by Django 3.2.6 on 2021-09-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glav', '0004_auto_20210901_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Dropdown_for',
        ),
        migrations.DeleteModel(
            name='Dropdown_one',
        ),
        migrations.DeleteModel(
            name='Dropdown_three',
        ),
        migrations.DeleteModel(
            name='Dropdown_two',
        ),
    ]
