# Generated by Django 3.2.6 on 2021-09-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glav', '0006_contacts_dropdown_for_dropdown_one_dropdown_three_dropdown_two'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Dropdown_for',
        ),
        migrations.DeleteModel(
            name='Dropdown_one',
        ),
        migrations.DeleteModel(
            name='Dropdown_three',
        ),
        migrations.DeleteModel(
            name='Dropdown_two',
        ),
    ]
