# Generated by Django 3.2.6 on 2021-09-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glav', '0008_contacts_dropdown_for_dropdown_one_dropdown_three_dropdown_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('datab', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('datas', models.DateTimeField(auto_now=True, verbose_name='Дата последного добавления')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фотография')),
                ('is_pblished', models.BooleanField(default=True, verbose_name='Публирован')),
            ],
            options={
                'verbose_name': 'Последние новости',
                'verbose_name_plural': 'Последние новости',
            },
        ),
    ]
