# Generated by Django 3.2.6 on 2021-09-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glav', '0009_last_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Last_new',
        ),
    ]
