# Generated by Django 3.2.6 on 2021-08-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos_one/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
